[ubuntu]
10.0.101.236
10.0.102.224
10.0.101.36

[amazon]
10.0.101.206
10.0.102.82
10.0.101.44

[ubuntu:vars]
ansible_user=ubuntu

[amazon:vars]
ansible_user=ec2-user

[all:vars]
ansible_ssh_private_key_file=~/.ssh/spa.pem
